version: '3'
services:
  web-db:
    build: ./db
    restart: always
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
    - db-data:/var/lib/postgresql/data

  web:
    depends_on:
      - web-db
    build:
      context: ..
      dockerfile: ./docker/webapp/Dockerfile
    restart: always
    ports:
      - "80:5000"
    restart: always

volumes:
  db-data:

